version: '3.9'

services:

  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.main:app --host 0.0.0.0'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/db
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    ports:
      - 5432:5432

volumes:
  db-data: